const postgres = require('./postgres.js');
const expect_one_row_count = require('./expect_one_row_count.js');

module.exports = async (purchase) => {
    const text = 
    `
        INSERT INTO "purchases" (
            "internal_purchase_id",
            "user_id",
            "sale_item_key",
            "sale_item_price",
            "game_id",
            "t_created_purchase",
            "t_modified_purchase",
            "client_generated_idempotency_key",
            "game_credited_result",
            "purchase_result",
            "t_created_create_card",
            "t_modified_create_card",
            "create_card_idempotency_key",
            "create_card_result",
            "public_key_result",
            "create_card_id",
            "t_created_payment_3ds",
            "t_modified_payment_3ds",
            "payment_3ds_idempotency_key",
            "payment_3ds_result",
            "payment_3ds_id",
            "t_created_payment_cvv",
            "t_modified_payment_cvv",
            "payment_cvv_idempotency_key",
            "payment_cvv_result",
            "payment_cvv_id",
            "t_created_payment_unsecure",
            "t_modified_payment_unsecure",
            "payment_unsecure_idempotency_key",
            "payment_unsecure_result",
            "payment_unsecure_id",
            "metadata_hash_email",
            "metadata_hash_phone_number",
            "metadata_hash_session_id",
            "metadata_hash_ip_address",
            "metadata_hash_name_on_card",
            "metadata_hash_city",
            "metadata_hash_country",
            "metadata_hash_district",
            "metadata_hash_address_line_1",
            "metadata_hash_address_line_2",
            "metadata_hash_postal_zip_code",
            "metadata_hash_expiry_month",
            "metadata_hash_expiry_year",
            "metadata_hash_circle_public_key_id"
        ) VALUES (
             $1,  $2,  $3,  $4,  $5,  $6,  $7,  $8,  $9, $10, 
            $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 
            $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, 
            $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, 
            $41, $42, $43, $44, $45
        );
    `;
    const values = [
        purchase.internal_purchase_id,              // "internal_purchase_id",
        purchase.user_id,                           // "user_id",
        purchase.sale_item_key,                     // "sale_item_key",
        purchase.sale_item_price,                   // "sale_item_price",
        purchase.game_id,                           // "game_id",
        purchase.t_created_purchase,                // "t_created_purchase",
        purchase.t_modified_purchase,               // "t_modified_purchase",
        purchase.client_generated_idempotency_key,  // "client_generated_idempotency_key",
        purchase.game_credited_result,              // "game_credited_result",
        purchase.purchase_result,                   // "purchase_result",
        purchase.t_created_create_card,             // "t_created_create_card",
        purchase.t_modified_create_card,            // "t_modified_create_card",
        purchase.create_card_idempotency_key,       // "create_card_idempotency_key",
        purchase.create_card_result,                // "create_card_result",
        purchase.public_key_result,                 // "public_key_result",
        purchase.create_card_id,                    // "create_card_id",
        purchase.t_created_payment_3ds,             // "t_created_payment_3ds",
        purchase.t_modified_payment_3ds,            // "t_modified_payment_3ds",
        purchase.payment_3ds_idempotency_key,       // "payment_3ds_idempotency_key",
        purchase.payment_3ds_result,                // "payment_3ds_result",
        purchase.payment_3ds_id,                    // "payment_3ds_id",
        purchase.t_created_payment_cvv,             // "t_created_payment_cvv",
        purchase.t_modified_payment_cvv,            // "t_modified_payment_cvv",
        purchase.payment_cvv_idempotency_key,       // "payment_cvv_idempotency_key",
        purchase.payment_cvv_result,                // "payment_cvv_result",
        purchase.payment_cvv_id,                    // "payment_cvv_id",
        purchase.t_created_payment_unsecure,        // "t_created_payment_unsecure",
        purchase.t_modified_payment_unsecure,       // "t_modified_payment_unsecure",
        purchase.payment_unsecure_idempotency_key,  // "payment_unsecure_idempotency_key",
        purchase.payment_unsecure_result,           // "payment_unsecure_result",
        purchase.payment_unsecure_id,               // "payment_unsecure_id",
        purchase.metadata.email,                    // "metadata_hash_email",
        purchase.metadata.phone_number,             // "metadata_hash_phone_number",
        purchase.metadata.session_id,               // "metadata_hash_session_id",
        purchase.metadata.ip_address,               // "metadata_hash_ip_address",
        purchase.metadata.name_on_card,             // "metadata_hash_name_on_card",
        purchase.metadata.city,                     // "metadata_hash_city",
        purchase.metadata.country,                  // "metadata_hash_country",
        purchase.metadata.district,                 // "metadata_hash_district",
        purchase.metadata.address_line_1,           // "metadata_hash_address_line_1",
        purchase.metadata.address_line_2,           // "metadata_hash_address_line_2",
        purchase.metadata.postal_zip_code,          // "metadata_hash_postal_zip_code",
        purchase.metadata.expiry_month,             // "metadata_hash_expiry_month",
        purchase.metadata.expiry_year,              // "metadata_hash_expiry_year",
        purchase.metadata.circle_public_key_id      // "metadata_hash_circle_public_key_id"
    ];
    const result = await postgres.query(text, values);
    return expect_one_row_count(result);
};