CREATE TABLE "users" (
    "internal_user_id"     UUID NOT NULL,   -- the primary key and internal representation of this user
    "identification_hash"  UUID NOT NULL,   -- how the user is identified by the integrating service such as neon district (a hash of the user name or id)
    "t_created_internally" BIGINT NOT NULL, -- when the user record was created internally
    PRIMARY KEY ("internal_user_id")
);

CREATE TABLE "purchases" (
    "internal_purchase_id"               UUID NOT NULL,    -- the primary key and internal representation of this purchase
    "internal_user_id"                   UUID NOT NULL,    -- the foreign key of the user making this purchase
    "t_created_internally"               BIGINT NOT NULL,  -- when the purchase record was created internally
    "t_modified_internally"              BIGINT NOT NULL,  -- when the purchase record was last modified internally
    "sale_item_key"                      STRING NOT NULL,  -- the key used to represent the item being purchased, essentially a sku such as "NEON_1000_PACK"
    "sale_item_price"                    STRING NOT NULL,  -- the amount of usd currency charged for the item as a string such as "1.46" which is how circle handles dollar amounts
    "client_generated_idempotency_key"   UUID NOT NULL,    -- the idempotency key generated by the client for the purchase
    "denied_for_internal_validation"     BOOLEAN NOT NULL, -- a flag indicating if the purchase was denied outright due to internal validation issues (not circle validation)
    "metadata_hash_email"                STRING NOT NULL,
    "metadata_hash_phone"                STRING NOT NULL,
    "metadata_hash_session_id"           STRING NOT NULL,
    "metadata_hash_ip_address"           STRING NOT NULL,
    "metadata_hash_name_on_card"         STRING NOT NULL,
    "metadata_hash_city"                 STRING NOT NULL,
    "metadata_hash_country"              STRING NOT NULL,
    "metadata_hash_district"             STRING NOT NULL,
    "metadata_hash_address_1"            STRING NOT NULL,
    "metadata_hash_address_2"            STRING NOT NULL,
    "metadata_hash_postal_zip_code"      STRING NOT NULL,
    "metadata_hash_expiry_month"         STRING NOT NULL,
    "metadata_hash_expiry_year"          STRING NOT NULL,
    "metadata_hash_card_number"          STRING NOT NULL,
    "metadata_hash_card_cvv"             STRING NOT NULL,
    "metadata_hash_circle_public_key_id" STRING NOT NULL,

    PRIMARY KEY ("internal_purchase_id"),
    CONSTRAINT "fk_internal_user_id" FOREIGN KEY("internal_user_id") REFERENCES "users"("internal_user_id")
);

enum event type
add card request
add card response
create purchase request
create purchase response

CREATE TABLE "purchase_event" (
    "internal_purchase_event_id" UUID NOT NULL,

);

CREATE TABLE "purchase_event_create_card_request" (

);

CREATE TABLE "purchase_event_create_card_response" (

);

CREATE TABLE "purchase_event_create_purchase_request" (

);

CREATE TABLE "purchase_event_create_purchase_response" (

);

